I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 206, in script
    scene universe
  File "game/script.rpy", line 206, in <module>
    scene universe
TypeError: __init__() takes at least 4 arguments (2 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 206, in script
    scene universe
  File "F:\Utilitaires\renpy-7.3.5-sdk\renpy\ast.py", line 1013, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "F:\Utilitaires\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 206, in <module>
    scene universe
TypeError: __init__() takes at least 4 arguments (2 given)

Windows-8-6.2.9200
Ren'Py 7.3.5.606
EthiQuest 1.0
Tue May 05 11:30:52 2020
